/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.programa07;
import java.util.List;
import javax.swing.JOptionPane;
import org.uv.DAO.DAOProducto;
import org.uv.Entyties.Producto;
/**
 *
 * @author juand
 */
public class Creacion extends javax.swing.JFrame {
    protected DAOProducto daoPro = new DAOProducto();
    /**
     * Creates new form Creacion
     */
    public Creacion() {
        initComponents();
        inicio();
    }
    
    private void inicio(){
        List <Producto> lp=daoPro.findAll();
        if(lp.size()>0){
            Producto p=lp.get(lp.size()-1);
            IDEntrada.setText(String.valueOf(p.getId_producto()+1));
        }else{
             IDEntrada.setText("1");       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        DescripcionEntrada = new javax.swing.JTextField();
        PrecioEntrada = new javax.swing.JTextField();
        StockEntrada = new javax.swing.JTextField();
        IDEntrada = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        ID.setText("ID:");

        Descripcion.setText("Descripcion:");

        Precio.setText("Precio:");

        Stock.setText("Stock:");

        IDEntrada.setText("aqui ira el ID");

        Confirmar.setIcon(new javax.swing.ImageIcon("D:\\6toSemestre\\Desarrollo de aplicaciones\\NetBeansProjects\\Programa06\\src\\main\\java\\org\\uv\\Imagenes\\guardar.png")); // NOI18N
        Confirmar.setText("Aceptar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        Regresar.setIcon(new javax.swing.ImageIcon("D:\\6toSemestre\\Desarrollo de aplicaciones\\NetBeansProjects\\Programa06\\src\\main\\java\\org\\uv\\Imagenes\\regresar.png")); // NOI18N
        Regresar.setText("Cancelar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Descripcion)
                            .addComponent(Precio)
                            .addComponent(Stock)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Confirmar)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StockEntrada)
                            .addComponent(PrecioEntrada)
                            .addComponent(DescripcionEntrada)
                            .addComponent(IDEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Regresar)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(IDEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcion)
                    .addComponent(DescripcionEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio)
                    .addComponent(PrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stock)
                    .addComponent(StockEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmar)
                    .addComponent(Regresar))
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ejecucion(){
        try{
            Producto p=new Producto(Integer.parseInt(IDEntrada.getText()), DescripcionEntrada.getText(), Float.parseFloat(PrecioEntrada.getText()), Float.parseFloat(StockEntrada.getText()));
            daoPro.create(p);
            JOptionPane.showMessageDialog(null, "Productos guardado con exito!");
            inicio();
            DescripcionEntrada.setText("");
            PrecioEntrada.setText("");
            StockEntrada.setText("");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ingrese datos validos.\n"+ex.getMessage());
        }
    }
    
    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        ejecucion();
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Confirmar;
    private javax.swing.JLabel Descripcion;
    protected javax.swing.JTextField DescripcionEntrada;
    private javax.swing.JLabel ID;
    protected javax.swing.JLabel IDEntrada;
    private javax.swing.JLabel Precio;
    protected javax.swing.JTextField PrecioEntrada;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel Stock;
    protected javax.swing.JTextField StockEntrada;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
