/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.programa07;

import javax.swing.JOptionPane;
import org.uv.Entyties.Producto;
/**
 *
 * @author juand
 */
public class Modificacion extends Creacion {

    /**
     * Creates new form Modificacion
     */
    public Modificacion(Producto p) {
        initComponents();
        IDEntrada.setText(String.valueOf(p.getId_producto()));
        DescripcionEntrada.setText(p.getDescripcion());
        PrecioEntrada.setText(String.valueOf(p.getPrecio_unitario()));
        StockEntrada.setText(String.valueOf(p.getStock()));
    }
    
    @Override
    public void ejecucion(){
        try{
            Producto p=new Producto(Integer.parseInt(IDEntrada.getText()), DescripcionEntrada.getText(), Float.parseFloat(PrecioEntrada.getText()), Float.parseFloat(StockEntrada.getText()));
            daoPro.update(p, p.getId_producto());
            JOptionPane.showMessageDialog(null, "Productos modificado con exito!");
            dispose();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ingrese datos validos.\n"+ex.getMessage());
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
